[project]
name = "jaffle-shop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dbt-bigquery~=1.8.0",
    "dbt-core~=1.8.0",
    "mpire[dill]>=2.10.2",
]
